[package]
name = "sudoku"
version = "0.1.0"
authors = ["Yuri Brandi <y.brandi@studenti.unisa.it>"]
license = "MIT"
edition = "2024"

[dependencies]
egui = "0.32.1"
eframe = "0.32.1"
rand = "0.9.2"
image = "0.25.6"
varisat = "0.2.2"